---
title: "Midterm Project"
author: "Ang Li"
date: "2017/11/13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("RMySQL")  # you may have to install first
library(RMySQL)
library(lme4)
library(arm)
library(dplyr)
```

```{r}
mydb = dbConnect(MySQL(), user='mssp', password='mssp2017', dbname='yelp_db', host='45.63.90.29')
```

```{r}
dbListTables(mydb) 
#This will return a list of the tables in our connection. 
```

```{r}
dbListFields(mydb, 'business') # eg: have a look what variables are in 'user' table
#This will return a list of the fields(columns) in table 'user'. 

#dbListFields(mydb, 'friend')
```

```{r}
business.sql = dbSendQuery(mydb, "
                          select * 
                           from business 
                           " )  # still in mysql
business = fetch(business.sql, n = -1)   # fetch back to R
```

```{r}
#head(business)
 business %>%
summarise(count_all = n_distinct(state))
fit<-lmer(stars~review_count+is_open+(1|state), data=business)
display(fit)
```